### ISSUE TITLE
Problème de réutilisation de fonctions

### ISSUE THREAD

**Issue by HURTELJoris** [QuentinPOL/TP-SYSTEMES#1]
Un grand bonjour à M.Pollet et à tous ses collègues et collaborateurs. Je vous contacte en ce jour car nous avons fait on fork de votre projet mon groupe et moi. Cependant, il y a un problème au niveau de l'encapsulation de vos classes. Nous ne pouvons donc pas les réutiliser sans lire et comprendre le code. Impossible donc de réutiliser le code de gestion de la carte indépendamment de l’IHM ou du système d'Eclairage d'un plateau de créateur de contenu. De plus, nous avons environ 244 erreurs. Cela doit être supposément dû à votre version de Visual Studio. Nous avons installé la version x32 et nous sommes passé de 244 erreurs à 1713 ERREURS. Cela est inacceptable.
Vous vous devez de réparer ces problèmes sous peu, dès que possible !

Cordialement, Joris HURTEL & Groupe ©2023

**Comment by QuentinPOL** [comment]
Bonjour, problème régler !

**Comment by HURTELJoris** [comment]
Merci bien très chère collègue :)
